name: "Release"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
          echo "VIPS_VERSION=8.12.2" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=1" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./bin/build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Lambda Layer Container
        run: |
          echo "${{ secrets.PUBLIC_GITHUB_TOKEN_PACKAGES }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          ./bin/deploy
