name: "Release"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: |
          echo "VIPS_VERSION=8.12.2" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=1" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Run Development Container
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/customink/ruby-vips-lambda-devcontainer
          runCmd: |
            ./bin/build
      - name: Get CHANGELOG Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          validation_level: warn
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Push Lambda Extension Layer Image
        run: |
          echo "${{ secrets.PUBLIC_GITHUB_TOKEN_PACKAGES }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          ./bin/deploy
